version: 0.2

env:
  variables:
    AWS_REGION: "ap-south-1"
    ECR_REPO: "792682046782.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app"
    CLUSTER_NAME: "brain-tasks-cluster"

phases:
  install:
    commands:
      - curl -LO "https://dl.k8s.io/release/v1.34.0/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - kubectl version --client
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -q -o awscliv2.zip
      - ./aws/install --update
      - aws --version
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG $ECR_REPO:latest
  post_build:
    commands:
      - docker push $ECR_REPO:$IMAGE_TAG
      - docker push $ECR_REPO:latest
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION
      - kubectl set image deployment/brain-tasks-app brain-tasks-app=$ECR_REPO:$IMAGE_TAG
      - kubectl rollout status deployment/brain-tasks-app
